_nutritracker_front/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from users.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('foods/', include(('foods.urls', 'foods'), namespace='foods')),
    path('recipes/', include(('recipes.urls', 'recipes'), namespace='recipes')),
    path('diaries/', include(('diaries.urls', 'diaries'), namespace='diaries')),
    path('utils/', include(('utils.urls', 'utils'), namespace='utils')),
    path('', index, name='index'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foods/urls.py
from django.urls import path

from .views import (
    FoodDataView, FoodCategoryList,
    CategoryFoodsView, FoodMaxNutrientsView,
    CompareFoodsView, CompareFoodsListPageView
    )

from .views_ajax import (
    get_food_data_for_comparison_ajax,
    food_suggestions_ajax,
    compare_food_suggestions_ajax
)


urlpatterns = [
    path('', FoodCategoryList.as_view(), name='food_category_list'),
    path('category_<slug:category_slug>/', CategoryFoodsView.as_view(), name='food_category'),
    
    path('compare_food_suggestions/', compare_food_suggestions_ajax, name='compare_food_suggestions'),
    path('compare_<slug:food_slug>/', CompareFoodsListPageView.as_view(), name='compare_foods_list_page'),
    path('<slug:primary_slug>-vs-<slug:secondary_slug>/', CompareFoodsView.as_view(), name='compare_foods'),
    path('max_<slug:nutrient_slug>/', FoodMaxNutrientsView.as_view(), name='max_nutrients'),
    path('get_food_data_for_comparison/', get_food_data_for_comparison_ajax, name='get_food_data_for_comparison'),
    path('food_suggestions/', food_suggestions_ajax, name='food_suggestions'),
    path('<slug:food_slug>/', FoodDataView.as_view(), name='food'),
]

foods/models.py
from django.db import models

# Create your models here.

foods/views.py
import requests

from django.shortcuts import render

from django.views import View
from django.conf import settings

from utils.services import get_base_url
from .services import (
    get_category_list, get_current_category,
    get_category_foods, get_food_list_to_compare,
    get_food_data, get_max_nutrient_food_list,
    get_compare_food_facts, get_child_categories
)

class FoodDataView(View):
    def get(self, request, food_slug):
        comparison_foods = get_food_list_to_compare(request)
        food = get_food_data(request, food_slug)
        menu_categories = get_category_list(request)
        context = {
            'food': food,
            'comparison_foods': comparison_foods,
            'menu_categories': menu_categories,
        }

        return render(request, 'foods/food_data.html', context)
    

class FoodCategoryList(View):
    def get(self, request):
        menu_categories = get_category_list(request)
        context = {
            'menu_categories': menu_categories,
        }
        return render(request, 'foods/food_category_list.html', context)
    

class CategoryFoodsView(View):
    def get(self, request, category_slug):
        current_category = get_current_category(request, category_slug)
        child_categories = get_child_categories(request, category_slug)
        food_categories = {}
        if child_categories != []:
            for child_category in child_categories:
                food_categories[child_category['name']] = get_category_foods(request, child_category['slug'])
        else:
            food_categories[current_category['name']] = get_category_foods(request, category_slug)
        menu_categories = get_category_list(request)

        context = {
            'current_category': current_category,
            'food_categories': food_categories,
            'menu_categories': menu_categories
        }
        
        return render(request, 'foods/food_category.html', context)
    

class FoodMaxNutrientsView(View):
    def get(self, request, nutrient_slug):
        foods = get_max_nutrient_food_list(request, nutrient_slug)
        menu_categories = get_category_list(request)

        context = {
            'foods': foods,
            'menu_categories': menu_categories,
        }

        return render(request, 'foods/max_nutrient.html', context)
    

class CompareFoodsView(View):
    def get(self, request, primary_slug, secondary_slug):
        primary_food = get_food_data(request, primary_slug)
        secondary_food = get_food_data(request, secondary_slug)
        compare_food_facts = get_compare_food_facts(
            request, 
            primary_slug, 
            secondary_slug
            )
        
        primary_food_nutrients = primary_food['food_nutrients']
        secondary_food_nutrients = secondary_food['food_nutrients']
        all_food_nutrients = list(zip(primary_food_nutrients, secondary_food_nutrients))

        comparison_foods = get_food_list_to_compare(request)
        import json
        print('!!', json.dumps(all_food_nutrients, indent=2))
        context = {
            'primary_food': primary_food,
            'secondary_food': secondary_food,
            'compare_food_facts': compare_food_facts,
            'all_food_nutrients': all_food_nutrients,
            'comparison_foods': comparison_foods
        }

        return render(request, 'foods/food_comparison.html', context)
    

class CompareFoodsListPageView(View):
    def get(self, request, food_slug):
        foods = get_food_list_to_compare(request, food_slug)
        menu_categories = get_category_list(request)
        
        context = {
            'foods': foods,
            'menu_categories': menu_categories,
            'food_slug': food_slug
        }

        return render(request, 'foods/compare_foods_list_page.html', context)

foods/templates/foods/__compare_food_suggestions.html
{% for value in values %}
    <div class="suggestions-value-button suggestion-{{model}}" data-slug='{{value.1}}' onclick="set_suggestion_value(event)">{{value.0}}</div>
{% endfor %}

foods/templates/foods/__food_suggestions.html
{% for value in values %}
    <div class="suggestions-value-button suggestion-{{model}}" onclick="window.location='{{value.2}}'">{{value.0}}</div>
{% endfor %}

foods/templates/foods/_category_menu.html
<div class='block-shadow px-4 py-3 hide-mobile' style="width:200px">
    <div class='category-menu-items'>
        {% for category in menu_categories %}
        <a 
        class='category-menu-item-link' 
        href="{% url 'foods:food_category' category.slug %}"
        id="category-{{category.slug}}"
        >
        {{category.name}}
    </a>
    {% endfor %}
    </div>
</div>

foods/templates/foods/_comparison_block.html
{% load static mathfilters %}
<script>
    var amount = 100
</script>

<div style="display:flex; gap:20px; align-items: center;">
    <div style='display:flex; gap:8px'>
        <div style="width:84px;">{{p_food.content|mul:100|floatformat:1}} {{p_food.nutrient.rda_unit}}</div>
        <div style="width:50px;">{{p_food.ratio|mul:100|mul:100|floatformat:1}}%</div>
    </div>
    
    <div style="display:flex; position:relative; width:var(--bar-width); justify-content: flex-end;">
        <div style="align-self:flex-end; width:calc({{p_food.ratio}} * var(--bar-width) * 100); max-width:var(--bar-width); height:12px; background-color:{{p_food.color}}; border-radius:4px"></div>
    </div>


    <div style="width:180px; margin:auto; text-align:center; overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">{{p_food.nutrient.name}}</div>
    
    
    <div style="display:flex; position:relative; width:var(--bar-width)">
        <div style="width:calc({{s_food.ratio}} * var(--bar-width) * 100); max-width:var(--bar-width); height:12px; background-color:{{s_food.color}}; border-radius:4px"></div>
    </div>
    <div style='display:flex; gap:8px'>
        <div style="width:50px;">{{s_food.ratio|mul:100|mul:100|floatformat:1}}%</div>
        <div style="width:80px;">{{s_food.content|mul:100|floatformat:1}} {{s_food.nutrient.rda_unit}}</div>
    </div>
</div>    

foods/templates/foods/_nutrient_table_row.html
{% load mathfilters %}

<tr>
    <td class=" mobile-padding-0"><a class="no-decoration-link" style='width:340px; word-wrap: break-word;' href="{% url 'foods:max_nutrients' food_nutrient.nutrient.slug %}">
            {{ food_nutrient.nutrient.name }}
        </a>
    </td>
    <td><span class='content-cell' data-content="{{food_nutrient.content|floatformat}}">{{ food_nutrient.content|mul:100|floatformat }}</span> {{food_nutrient.nutrient.rda_unit}}</td>
    <td>
        {% if food_nutrient.nutrient.rda_male %}
            {{ food_nutrient.nutrient.rda_male }} {{food_nutrient.nutrient.get_rda_unit_display}}
        {% endif %}
    </td>
    <td>
        <div 
            class='nutrient-bar' 
            data-ratio='{{food_nutrient.ratio}}' 
            style="width:calc({{food_nutrient.ratio}} * var(--bar-width) * 100); 
                max-width:var(--bar-width); 
                position: absolute; 
                height:20px; 
                background-color:red; 
                border-radius:20px"
                >
                {{ food_nutrient.nutrient.rda }}
        </div>
    </td>
</tr>

foods/templates/foods/_nutrients.html
{% load mathfilters%}

<table class="table nutri-table mt-3" style="">
    <thead style="background-color:rgb(183, 230, 203)">
        <th style="width:2.5em"></th>
        <th style="width:340px; word-wrap: break-word;">Нутриент</th>
        <th>кол-во</th>
        <th>РСП</th>
        <th>% РСП</th>
    </thead>
    <tbody>
        
        <!-- <td rowspan=8 class='td-sidebar' style="background-color:rgb(221, 100, 100);"><div>Макронутриенты</div></td> -->
        
        {% regroup food.food_nutrients by type_name_rus_plural_nominative as types %}
        {% for type in types %}
        <td rowspan={{type.list|length|add:1}} class='td-sidebar' style="background-color:{{type.list.0.color}};"><div>{{type.grouper}}</div></td>
                {% for food_nutrient in type.list %}
                    {% include 'foods/_nutrient_table_row.html' %}
                {% endfor %}
        {% endfor %}

        
    </tbody>
</table>

foods/templates/foods/_nutrients_backup.html
<div class="nutri-block mt-4 block-shadow px-4 py-3">
    <div style="width:100%">Макронутриенты</div>
    <div class='nutri-block-inner' >
        {% for food_nutrient in food.food_nutrients %}
            {% if food_nutrient.nutrient.type == 'Macro' and food_nutrient.nutrient.display %}
                {% include 'foods/_nutrients_bars.html' %}
            {% endif %}
        {% endfor %}
    </div>
</div>
<div class="nutri-block mt-4 block-shadow px-4 py-3">
    <div style="width:100%">Водорастворимые витамины</div>
    <div class='nutri-block-inner' >
        {% for food_nutrient in food.food_nutrients %}
            {% if food_nutrient.nutrient.type == 'Vitamin_water' and food_nutrient.nutrient.display %}
                {% include 'foods/_nutrients_bars.html' %}
            {% endif %}
        {% endfor %}
    </div>
</div>
<div class="nutri-block mt-4 block-shadow px-4 py-3">
    <div style="width:100%">Жирорастворимые витамины</div>
    <div class='nutri-block-inner' >
        {% for food_nutrient in food.food_nutrients %}
            {% if food_nutrient.nutrient.type == 'Vitamin_fat' and food_nutrient.nutrient.display %}
                {% include 'foods/_nutrients_bars.html' %}
            {% endif %}
        {% endfor %}
    </div>
</div>
<div class="nutri-block mt-4 block-shadow px-4 py-3">
    <div style="width:100%">Минералы</div>
    <div class='nutri-block-inner' >
        {% for food_nutrient in food.food_nutrients %}
            {% if food_nutrient.nutrient.type == 'Mineral' and food_nutrient.nutrient.display %}
                {% include 'foods/_nutrients_bars.html' %}
            {% endif %}
        {% endfor %}
    </div>
</div>
<div class="nutri-block mt-4 block-shadow px-4 py-3">
    <div style="width:100%">Жирные кислоты</div>
    <div class='nutri-block-inner' >
        {% for food_nutrient in food.food_nutrients %}
            {% if food_nutrient.nutrient.type == 'Fatty_acid' and food_nutrient.nutrient.display %}
                {% include 'foods/_nutrients_bars.html' %}
            {% endif %}
        {% endfor %}
    </div>
</div>

foods/templates/foods/_nutrients_bars.html
<div style="width:var(--bar-width)">
    <div style="margin-bottom: -5px">
        
        <a class="no-decoration-link" href="{% url 'foods:max_nutrients' food_nutrient.nutrient.slug %}">
            {{ food_nutrient.nutrient.name }}
        </a>
    </div>

    <div style="position:relative">
        <div style="width:var(--bar-width); position:absolute; height:6px; background-color:grey; border-radius:20px"></div>
        <div class='nutrient-bar' data-ratio='{{food_nutrient.ratio}}' style="width:calc({{food_nutrient.ratio}} * var(--bar-width) * 100); max-width:var(--bar-width); position: absolute; height:6px; background-color:red; border-radius:20px">{{ food_nutrient.nutrient.rda }}
        </div>
    </div>
</div>

foods/templates/foods/compare_foods_list_page.html
{% extends '_base.html' %}

{% block content %}

<div class='foods-main' style="display:flex; gap:100px">
    {% include 'foods/_category_menu.html' %}
    <div class="article-main d-flex flex-column">
        {% regroup foods by category_name as cats %}
        {% for cat in cats %}
        <div class="row w-100 mb-5">    
            <div class='col-sm-12'>{{cat.grouper}}</div>
                {% for food in cat.list %}
                   
                    <div class='col-sm-12 col-lg-6'>
                        <a href="{% url 'foods:compare_foods' primary_slug=food_slug secondary_slug=food.slug %}">{{food.name}}</a>
                    </div>
                 
                {% endfor %}
            </div>
            {% endfor %}
    </div>
</div>

{% endblock %}

foods/templates/foods/food_category.html
{% extends '_base.html' %}

{% block content %}

<div class='foods-main' style="display:flex; gap:100px">
    {% include 'foods/_category_menu.html' %}
    <div class="article-main d-flex flex-column" style=" gap:30px; flex-grow:1">
        <h1>{{current_category.name}}</h1>
   
        {% for category, foods in food_categories.items %}
            <div class="row w-100">
                {% if food_categories|length > 1 %}
                    <h3>{{category}}</h3>
                {% endif %}
                {% for food in foods %}
                    <div class="col-lg-6"><a href="{% url 'foods:food' food_slug=food.slug %}">{{food.name}}</a></div>
                {% endfor %}
            </div>
        {% endfor %}

    <div>Article goes here</div>
    </div>
</div>


{% endblock %}

foods/templates/foods/food_category_list.html
{% extends '_base.html' %}

{% block content %}

<div class='foods-main' style="display:flex; gap:100px">
    {% include 'foods/_category_menu.html' %}
    <div class="article-main" style="display:flex; flex-direction:column; gap:30px">
        <h1>Продукты</h1>
        <div>Article goes here</div>
    </div>
</div>  
    
    <div">
        <h2>{{ food.name }}</span>
    </div>
    <div style="height: 1000px; background-color: green">

    </div>



{% endblock %}

foods/templates/foods/food_comparison.html
{% extends '_base.html' %}

{% load static mathfilters %}

{% block content %}


<div class='foods-main' style="display:flex; gap:100px">
    {% include 'foods/_category_menu.html' %}
    <div class="food-main">
        <div class="compare-block block-shadow px-4 py-3" style="display:flex; gap:20px; align-items: center">
            <div class="position-ralative">
                <input 
                    id="input-1"
                    class='exp-input exp-input-required form-control form-control-lg auto-search' 
                    type="text"  
                    placeholder="название продукта..."
                    onclick="get_suggestions(event)"
                    onkeyup="get_suggestions(event)">
                <div id='suggestions-Item' class="suggestions"></div>
            </div>
            <div style="width:max-content; white-space:nowrap;">Сравнить с:</div>
            <div class="position-ralative">
                <input 
                    id='input-2'
                    class='exp-input exp-input-required form-control form-control-lg auto-search' 
                    type="text"  
                    placeholder="название продукта..."
                    onclick="get_suggestions(event)"
                    onkeyup="get_suggestions(event)">
                <div id='suggestions-Item' class="suggestions"></div>
            </div>
            <button class="btn btn-primary" onclick="compare_products()">Сравнить</button>
        </div>
        <h1>{{ primary_food.name }} vs {{secondary_food.name}}</h1>
        <div class="food-comparison-block">
        
            <div class="mb-5">
                <h3 class="text-center mb-4">Макронутриенты</h3>
                {% for p_food, s_food in all_food_nutrients %}
                    {% if p_food.type_name == 'Macro' and p_food.nutrient.display %}
                        {% include 'foods/_comparison_block.html' %}
                    {% endif %}
                {% endfor %}
            </div>
            <div class="mb-5">
                <h3 class="text-center mb-4">Водорастворимые витамины</h3>
                {% for p_food, s_food in all_food_nutrients %}
                    {% if p_food.type_name == 'Vitamin_water' and p_food.nutrient.display %}
                        {% include 'foods/_comparison_block.html' %}
                    {% endif %}
                {% endfor %}
            </div>
            <div class="mb-5">
                <h3 class="text-center mb-4">Жирорастворимые витамины</h3>
                {% for p_food, s_food in all_food_nutrients  %}
                    {% if p_food.type_name == 'Vitamin_fat' and p_food.nutrient.display %}
                        {% include 'foods/_comparison_block.html' %}
                    {% endif %}
                {% endfor %}
            </div>
            <div class="mb-5">
                <h3 class="text-center mb-4">Минералы</h3>
                {% for p_food, s_food in all_food_nutrients %}
                    {% if p_food.type_name == 'Mineral' and p_food.nutrient.display %}
                        {% include 'foods/_comparison_block.html' %}
                    {% endif %}
                {% endfor %}
            </div>
            <div class="mb-5">
                <h3 class="text-center mb-4">Жирные кислоты</h3>
                {% for p_food, s_food in all_food_nutrients %}
                    {% if p_food.type_name == 'Fatty_acid' and p_food.nutrient.display %}
                        {% include 'foods/_comparison_block.html' %}
                    {% endif %}
                {% endfor %}
            </div>
            
            </div>
        </div>
    </div>
</div>



<script>
    var suggestions_url = '{% url "foods:compare_food_suggestions" %}'
    $(window).on('DOMContentLoaded', ()=>{
        input_1 = document.getElementById('input-1')
        input_2 = document.getElementById('input-2')
        input_1.value = '{{primary_food.name}}'
        input_1.setAttribute('data-slug', '{{primary_food.slug}}')
        input_2.value = '{{secondary_food.name}}'
        input_2.setAttribute('data-slug', '{{secondary_food.slug}}')
    })

    function compare_products(){
        foods = [document.getElementById('input-1').dataset.slug,
                document.getElementById('input-2').dataset.slug].sort()
        primary = foods[0]
        secondary = foods[1]

        url = '/foods/' + primary + '-vs-' + secondary + '/'
        window.location = url
        
    }
</script>
{% endblock %}

foods/templates/foods/food_data.html
{% extends '_base.html' %}

{% block content %}
<div class='foods-main'>
    {% include 'foods/_category_menu.html' %}
    <div class="food-main">
        <h1>{{ food.name }}</h1>
        <div>{{ food.desc }}</div>
        <div class="tags-block">
            <h2>Тэги:</h2>
            <div class="tags">
                {% for tag in food.tags %}
                <div class='tag btn btn-sm btn-outline-secondary' style="display:flex; align-items:center; gap:8px">
                    <!-- <img hight=32 width=32 v-if='tag.icon' :src="'http://127.0.0.1:8000' + tag.icon"> -->
                    <div>{{ tag.tag }}</div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div style="display:flex; gap:32px;">
            <div style="width:100%">
                <div class="amount-block block-shadow px-4 py-3">
                    Количество:
                    <input id='food-amount-field' type="number" class='form-control' style="width:100px" value="100" min="0">
                </div>
                {% include 'foods/_nutrients.html' %}
            </div>
        </div>
        <div class="mt-5">
            <h2>Часто задаваемые вопросы</h2>
        </div>
        <div class="mt-5">
            <h2>Способы обработки</h2>
        </div>
        <a href="{% url 'foods:compare_foods_list_page' food_slug=food.slug %}">Сравните {{food.name}} с другими продуктами</a>
    </div>
</div>


<script>
    $('#comparison-select').on('change', (e) => {
        get_data_for_compared_product(e.target.value)
    })

    $(window).on('DOMContentLoaded', ()=>{
        calculate_bars()
    })

    $('#food-amount-field').on('change keyup', () => {
        var amount = document.getElementById('food-amount-field').value
        calculate_contents(amount)
        calculate_bars(amount)
    })

    function calculate_contents(amount){
        var content_cells = document.getElementsByClassName('content-cell')
        for (var cell of content_cells){
            content = cell.dataset.content
            cell.innerHTML = (content * amount).toFixed(1)
        }
    }

    function calculate_bars(amount){
        
        var bars = document.getElementsByClassName('nutrient-bar')
        var bar_width = getComputedStyle(document.body)
        bar_width = bar_width.getPropertyValue('--bar-width')
        for (var bar of bars){
            ratio = bar.dataset.ratio
            bar.style.width = 'calc(' + bar_width + ' * ' + amount + ' * ' + ratio + ' )'
        }
    }

    function get_data_for_compared_product(food_slug){

        $.ajax({
            type: 'GET',
            url: "{% url 'foods:get_food_data_for_comparison' %}",
            data: {
                food_slug: food_slug
            },
            success: function(json){
                document.getElementById('compare-food-data').innerHTML=json['result']
            }
        })
    }
</script>
{% endblock %}

foods/templates/foods/max_nutrient.html
{% extends '_base.html' %}

{% block content %}
{% for food in foods %}
    {{food.name}}
{% endfor %}

{% endblock %}