_nutritracker_front/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from users.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('foods/', include(('foods.urls', 'foods'), namespace='foods')),
    path('recipes/', include(('recipes.urls', 'recipes'), namespace='recipes')),
    path('diaries/', include(('diaries.urls', 'diaries'), namespace='diaries')),
    path('utils/', include(('utils.urls', 'utils'), namespace='utils')),
    path('', index, name='index'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foods/urls.py
from django.urls import path

from .views import (
    FoodDataView, FoodCategoryList,
    CategoryFoodsView, FoodMaxNutrientsView,
    CompareFoodsView, CompareFoodsListPageView
    )

from .views_ajax import (
    get_food_data_for_comparison_ajax,
    food_suggestions_ajax,
    compare_food_suggestions_ajax
)


urlpatterns = [
    path('', FoodCategoryList.as_view(), name='food_category_list'),
    path('category_<slug:category_slug>/', CategoryFoodsView.as_view(), name='food_category'),
    
    path('compare_food_suggestions/', compare_food_suggestions_ajax, name='compare_food_suggestions'),
    path('compare_<slug:food_slug>/', CompareFoodsListPageView.as_view(), name='compare_foods_list_page'),
    path('<slug:primary_slug>-vs-<slug:secondary_slug>/', CompareFoodsView.as_view(), name='compare_foods'),
    path('max_<slug:nutrient_slug>/', FoodMaxNutrientsView.as_view(), name='max_nutrients'),
    path('get_food_data_for_comparison/', get_food_data_for_comparison_ajax, name='get_food_data_for_comparison'),
    path('food_suggestions/', food_suggestions_ajax, name='food_suggestions'),
    path('<slug:food_slug>/', FoodDataView.as_view(), name='food'),
]

recipes/urls.py
from django.urls import path

from .views import (
    RecipeListView,
)

urlpatterns = [
    path('', RecipeListView.as_view(), name='recipe_list'),
    # path('', update_recipe_list_ajax.as_view(), name='update_recipe_list'),
]

templates/_base.html
{% load static i18n %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{{page_titel}}{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <link href="https://fonts.googleapis.com/css2?family=Play:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Play:wght@400;700&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet"> 

    <link rel="stylesheet" type="text/css" href="{% static '/css/index.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/navbar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/diary.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/recipes.css' %}">

    
</head>

<body>

    <!-- login Modals -->
    {% include 'registration/_modal_signin.html' %}
    {% include 'registration/_modal_signup.html' %}
    {% include 'registration/_modal_pass_reset.html' %}


    {% include '_navbar.html' %}
    {% include '_sidebar.html' %}
    <div style="display: flex; justify-content: center">
        <div class='mobile-margin-auto' style='width: 1400px; margin: 70px 0 0 100px; padding: 20px;'>
            {% block content %}
            {% endblock %}
        </div>
      </div>
    </div>
    
    <!-- <script src="{% static '/js/functions.js' %}"></script> -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <script src="{% static '/js/suggestions.js' %}"></script>
</body>

</html>

templates/_navbar.html
<div class="navbar">
    <div><a href="{% url 'index' %}" class="navbar-logo">NutriTracker</a></div>
    <div class="navbar-main-menu hide-mobile">
        <div>
            <a href="{% url 'foods:food_category_list' %}">
                Продукты
            </a>
        </div>
        <div>Рецепты</div>
        <div>Статистика</div>
        <div>Врачи</div>
        <div>База знаний</div>
        <div>Статьи</div>
        
    </div>
    <div class="navbar-right-menu">
        {% if not users.is_authenticated %}
        <div class="navbar-auth-menu">
            <button data-bs-toggle="modal" data-bs-target="#sign-in-modal" class="btn btn-primary">Вход</button>
        </div>
        {% else %}
        <div style="display:flex; gap:20px">
            <div style="display:flex; gap:16px">
                <div class="navbar-profile-name" style="display:flex; flex-direction:column; align-items:flex-end">
                    <div style="margin-bottom:-4px">{{ profile.first_name }}</div>
                    <div>{{ profile.last_name }}</div>
                </div>
                <img height=50 width=50 src="'http://127.0.0.1:8000' + profile.avatar" style="object-fit:cover; border-radius:100px">
            </div>
            <button onclick="sign_out()" class="btn btn-secondary">Выход</button>
        </div>
        {% endif %}
    </div>
</div>

templates/_sidebar.html
{% load static %}

<div class="sidebar hide-mobile">
    <a href='#' class="sidebar-icon">
        <img width=24 height=24 src="{% static 'icons/dashboard.png' %}"/>
    </a>
    <a href='#' class="sidebar-icon">
        <img width=24 height=24 src="{% static 'icons/journal.png' %}"/>
    </a>
    <a href='{% url "recipes:recipe_list" %}' class="sidebar-icon">
        <img width=24 height=24 src="{% static 'icons/recipe-book.png' %}"/>
    </a>
    <a href='#' class="sidebar-icon">
        <img width=24 height=24 src="{% static 'icons/settings.png' %}"/>
    </a>
</div>

templates/index.html
{% extends '_base.html' %}
{% load static %}


{% block content %}


<div class="index-grid">
<div class="ig-search block-shadow p-4">
    <div class='ig-search-block'>
        <h3>Узнайте, что вы едите:</h3>
        <div class="position-ralative">
            <input 
                class='exp-input exp-input-required form-control form-control-lg auto-search' 
                type="text"  
                placeholder="название продукта..."
                onclick="get_suggestions(event)"
                onkeyup="get_suggestions(event)">
            <div id='suggestions-Item' class="suggestions"></div>
            <input class='form-control form-control-lg' type="file" name="image" accept="image/*" capture="environment">
        </div>
    </div>
    <img height='480' width='480' src="{% static 'images/salad_no_bg.png' %}" class='index-search-img'>
</div>
<div class="ig-compare">
    compare
</div>
<div class="ig-books block-shadow p-4" style="display:flex; flex-direction:column; align-items:center">
    <a href="#" class='no-underline-link black-link hover-underline'><h4 class='mt-3' style="text-align:center;">Подборка книг по нутрициологии от гуру</h4></a>
    <img class="mt-4" height='200' width='200' src="{% static 'images/photo4.jpg' %}" style="border-radius: 1000px">
    <div class='mt-3' style="font-size:1.8rem">Олег Никифоров</div>
    <div style="text-align:center; width:90%">эксперт по восстановлению здоровья с помощью питания</div>
    <div class='w-100' style="margin-top:auto; display:flex; flex-direction:column; gap:8px">
        <div style="display:flex; justify-content:space-between">
            <div style="display:flex; gap:4px">
                <i class="bi bi-globe text-secondary"></i>
                <div class="text-secondary">Телеграм</div>
            </div>
            <div>@x6703045</div>
        </div>
        <div style="display:flex; justify-content:space-between">
            <div style="display:flex; gap:4px">
                <i class="bi bi-telegram text-secondary"></i>
                <div class="text-secondary">Сайт</div>
            </div>
            <div>nikiforoff.ru</div>
        </div>
    </div>

</div>
<!-- <div class="ig-study">
    study
</div> -->

</div>

<script>

    var suggestions_url = '{% url "foods:food_suggestions" %}'
    

</script>
{% endblock %}